name: Sync main to data

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync and push to data branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/data; then
            git switch data
            git pull origin data
          else
            echo "Data branch does not exist. Exiting."
            exit 0
          fi
          git merge --no-ff origin/main -m "Merge main into data [skip ci]"
          git push origin data